"""add_servicio_fields_to_camion

Revision ID: c20f6966cb27
Revises: dd1866f46b4d
Create Date: 2026-02-06 18:40:18.548791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20f6966cb27'
down_revision = 'dd1866f46b4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camiones', sa.Column('ultimo_servicio', sa.Date(), nullable=True))
    op.add_column('camiones', sa.Column('ultimo_servicio_km', sa.Integer(), nullable=True))
    op.add_column('camiones', sa.Column('proximo_servicio_km', sa.Integer(), nullable=True))
    op.add_column('camiones', sa.Column('proximo_servicio_fecha', sa.Date(), nullable=True))
    op.add_column('camiones', sa.Column('intervalo_servicio_km', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('camiones', 'intervalo_servicio_km')
    op.drop_column('camiones', 'proximo_servicio_fecha')
    op.drop_column('camiones', 'proximo_servicio_km')
    op.drop_column('camiones', 'ultimo_servicio_km')
    op.drop_column('camiones', 'ultimo_servicio')
    # ### end Alembic commands ###
