"""add_nombre_and_cisterna_id_to_combustible

Revision ID: 14d1e2b3fbaf
Revises: ba84c64bd20b
Create Date: 2026-02-06 21:01:41.458663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d1e2b3fbaf'
down_revision = 'ba84c64bd20b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Agregar cisterna_id a cargas_cisterna
    op.add_column('cargas_cisterna', sa.Column('cisterna_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'cargas_cisterna', 'cisterna_combustible', ['cisterna_id'], ['id'])

    # Agregar nombre como nullable primero
    op.add_column('cisterna_combustible', sa.Column('nombre', sa.String(length=100), nullable=True))

    # Agregar nivel_minimo
    op.add_column('cisterna_combustible', sa.Column('nivel_minimo', sa.Numeric(precision=10, scale=2), nullable=True))

    # Actualizar registros existentes con valores por defecto
    op.execute("UPDATE cisterna_combustible SET nombre = 'Cisterna Principal' WHERE nombre IS NULL")
    op.execute("UPDATE cisterna_combustible SET nivel_minimo = nivel_alerta WHERE nivel_minimo IS NULL AND nivel_alerta IS NOT NULL")
    op.execute("UPDATE cisterna_combustible SET nivel_minimo = 1000 WHERE nivel_minimo IS NULL")

    # Ahora hacer nombre NOT NULL
    op.alter_column('cisterna_combustible', 'nombre', nullable=False)

    # Eliminar nivel_alerta
    op.drop_column('cisterna_combustible', 'nivel_alerta')

    # Agregar cisterna_id a suministros_combustible
    op.add_column('suministros_combustible', sa.Column('cisterna_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'suministros_combustible', 'cisterna_combustible', ['cisterna_id'], ['id'])

    # Actualizar cargas y suministros existentes con la primera cisterna
    op.execute("""
        UPDATE cargas_cisterna
        SET cisterna_id = (SELECT id FROM cisterna_combustible LIMIT 1)
        WHERE cisterna_id IS NULL
    """)
    op.execute("""
        UPDATE suministros_combustible
        SET cisterna_id = (SELECT id FROM cisterna_combustible LIMIT 1)
        WHERE cisterna_id IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suministros_combustible', type_='foreignkey')
    op.drop_column('suministros_combustible', 'cisterna_id')
    op.add_column('cisterna_combustible', sa.Column('nivel_alerta', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('cisterna_combustible', 'nivel_minimo')
    op.drop_column('cisterna_combustible', 'nombre')
    op.drop_constraint(None, 'cargas_cisterna', type_='foreignkey')
    op.drop_column('cargas_cisterna', 'cisterna_id')
    # ### end Alembic commands ###
