"""add_remito_fields_to_pesaje

Revision ID: ba84c64bd20b
Revises: c20f6966cb27
Create Date: 2026-02-06 20:35:58.170954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba84c64bd20b'
down_revision = 'c20f6966cb27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pesajes', sa.Column('acoplado', sa.String(length=20), nullable=True))
    op.add_column('pesajes', sa.Column('transportista', sa.String(length=100), nullable=True))
    op.add_column('pesajes', sa.Column('remitente', sa.String(length=100), nullable=True))
    op.add_column('pesajes', sa.Column('producto', sa.String(length=100), nullable=True))
    op.add_column('pesajes', sa.Column('numero_guia', sa.String(length=50), nullable=True))
    op.add_column('pesajes', sa.Column('operario', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pesajes', 'operario')
    op.drop_column('pesajes', 'numero_guia')
    op.drop_column('pesajes', 'producto')
    op.drop_column('pesajes', 'remitente')
    op.drop_column('pesajes', 'transportista')
    op.drop_column('pesajes', 'acoplado')
    # ### end Alembic commands ###
