"""Initial migration

Revision ID: dd1866f46b4d
Revises: 
Create Date: 2026-02-02 18:31:47.819823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1866f46b4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camiones',
    sa.Column('patente', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('año', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('VOLCADOR', 'ACOPLADO', 'MIXER', 'OTRO', name='tipocamionenum'), nullable=True),
    sa.Column('estado', sa.Enum('OPERATIVO', 'EN_SERVICIO', 'FUERA_SERVICIO', name='estadocamionenum'), nullable=False),
    sa.Column('kilometraje_actual', sa.Integer(), nullable=True),
    sa.Column('horometro_actual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('chofer_habitual', sa.String(length=100), nullable=True),
    sa.Column('foto', sa.String(length=500), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camiones_id'), 'camiones', ['id'], unique=False)
    op.create_index(op.f('ix_camiones_patente'), 'camiones', ['patente'], unique=True)
    op.create_table('cisterna_combustible',
    sa.Column('capacidad_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('nivel_actual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('nivel_alerta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cisterna_combustible_id'), 'cisterna_combustible', ['id'], unique=False)
    op.create_table('repuestos',
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('stock_actual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('proveedor', sa.String(length=255), nullable=True),
    sa.Column('ubicacion_deposito', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repuestos_codigo'), 'repuestos', ['codigo'], unique=True)
    op.create_index(op.f('ix_repuestos_id'), 'repuestos', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.Enum('ADMINISTRADOR', 'OPERADOR', 'SOLO_LECTURA', name='rolenum'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('cargas_cisterna',
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('litros', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('proveedor', sa.String(length=255), nullable=True),
    sa.Column('costo_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('costo_por_litro', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('numero_factura', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargas_cisterna_id'), 'cargas_cisterna', ['id'], unique=False)
    op.create_table('configuracion',
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.JSON(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracion_clave'), 'configuracion', ['clave'], unique=True)
    op.create_index(op.f('ix_configuracion_id'), 'configuracion', ['id'], unique=False)
    op.create_table('movimientos_stock',
    sa.Column('repuesto_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('INGRESO', 'EGRESO', name='tipomovimientoenum'), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('referencia_tipo', sa.String(length=50), nullable=True),
    sa.Column('referencia_id', sa.UUID(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuestos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_stock_id'), 'movimientos_stock', ['id'], unique=False)
    op.create_index(op.f('ix_movimientos_stock_repuesto_id'), 'movimientos_stock', ['repuesto_id'], unique=False)
    op.create_table('pesajes',
    sa.Column('numero_pesaje', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('camion_id', sa.UUID(), nullable=False),
    sa.Column('chofer', sa.String(length=100), nullable=True),
    sa.Column('peso_tara', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('peso_bruto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('peso_neto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('cliente_destino', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('remito_generado', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camion_id'], ['camiones.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pesajes_camion_id'), 'pesajes', ['camion_id'], unique=False)
    op.create_index(op.f('ix_pesajes_id'), 'pesajes', ['id'], unique=False)
    op.create_index(op.f('ix_pesajes_numero_pesaje'), 'pesajes', ['numero_pesaje'], unique=True)
    op.create_table('servicios',
    sa.Column('camion_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('PREVENTIVO', 'CORRECTIVO', 'EMERGENCIA', name='tiposervicioenum'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('kilometraje_servicio', sa.Integer(), nullable=True),
    sa.Column('horometro_servicio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mecanico', sa.String(length=255), nullable=True),
    sa.Column('costo_mano_obra', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('costo_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('PROGRAMADO', 'EN_PROCESO', 'COMPLETADO', name='estadoservicioenum'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('documentos', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camion_id'], ['camiones.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicios_camion_id'), 'servicios', ['camion_id'], unique=False)
    op.create_index(op.f('ix_servicios_id'), 'servicios', ['id'], unique=False)
    op.create_table('suministros_combustible',
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('camion_id', sa.UUID(), nullable=False),
    sa.Column('litros', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('chofer', sa.String(length=100), nullable=True),
    sa.Column('kilometraje', sa.Integer(), nullable=True),
    sa.Column('horometro', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camion_id'], ['camiones.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suministros_combustible_camion_id'), 'suministros_combustible', ['camion_id'], unique=False)
    op.create_index(op.f('ix_suministros_combustible_id'), 'suministros_combustible', ['id'], unique=False)
    op.create_table('remitos',
    sa.Column('numero_remito', sa.Integer(), nullable=False),
    sa.Column('pesaje_id', sa.UUID(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cliente', sa.String(length=255), nullable=False),
    sa.Column('producto', sa.String(length=100), nullable=False),
    sa.Column('peso_neto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('camion_patente', sa.String(length=20), nullable=True),
    sa.Column('chofer', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('enviado_email', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['pesaje_id'], ['pesajes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remitos_id'), 'remitos', ['id'], unique=False)
    op.create_index(op.f('ix_remitos_numero_remito'), 'remitos', ['numero_remito'], unique=True)
    op.create_table('servicios_repuestos',
    sa.Column('servicio_id', sa.UUID(), nullable=False),
    sa.Column('repuesto_id', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuestos.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicios_repuestos_id'), 'servicios_repuestos', ['id'], unique=False)
    op.create_index(op.f('ix_servicios_repuestos_repuesto_id'), 'servicios_repuestos', ['repuesto_id'], unique=False)
    op.create_index(op.f('ix_servicios_repuestos_servicio_id'), 'servicios_repuestos', ['servicio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servicios_repuestos_servicio_id'), table_name='servicios_repuestos')
    op.drop_index(op.f('ix_servicios_repuestos_repuesto_id'), table_name='servicios_repuestos')
    op.drop_index(op.f('ix_servicios_repuestos_id'), table_name='servicios_repuestos')
    op.drop_table('servicios_repuestos')
    op.drop_index(op.f('ix_remitos_numero_remito'), table_name='remitos')
    op.drop_index(op.f('ix_remitos_id'), table_name='remitos')
    op.drop_table('remitos')
    op.drop_index(op.f('ix_suministros_combustible_id'), table_name='suministros_combustible')
    op.drop_index(op.f('ix_suministros_combustible_camion_id'), table_name='suministros_combustible')
    op.drop_table('suministros_combustible')
    op.drop_index(op.f('ix_servicios_id'), table_name='servicios')
    op.drop_index(op.f('ix_servicios_camion_id'), table_name='servicios')
    op.drop_table('servicios')
    op.drop_index(op.f('ix_pesajes_numero_pesaje'), table_name='pesajes')
    op.drop_index(op.f('ix_pesajes_id'), table_name='pesajes')
    op.drop_index(op.f('ix_pesajes_camion_id'), table_name='pesajes')
    op.drop_table('pesajes')
    op.drop_index(op.f('ix_movimientos_stock_repuesto_id'), table_name='movimientos_stock')
    op.drop_index(op.f('ix_movimientos_stock_id'), table_name='movimientos_stock')
    op.drop_table('movimientos_stock')
    op.drop_index(op.f('ix_configuracion_id'), table_name='configuracion')
    op.drop_index(op.f('ix_configuracion_clave'), table_name='configuracion')
    op.drop_table('configuracion')
    op.drop_index(op.f('ix_cargas_cisterna_id'), table_name='cargas_cisterna')
    op.drop_table('cargas_cisterna')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_repuestos_id'), table_name='repuestos')
    op.drop_index(op.f('ix_repuestos_codigo'), table_name='repuestos')
    op.drop_table('repuestos')
    op.drop_index(op.f('ix_cisterna_combustible_id'), table_name='cisterna_combustible')
    op.drop_table('cisterna_combustible')
    op.drop_index(op.f('ix_camiones_patente'), table_name='camiones')
    op.drop_index(op.f('ix_camiones_id'), table_name='camiones')
    op.drop_table('camiones')
    # ### end Alembic commands ###
